In [20]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import optimize

In [21]:
numbers40 = np.array('''51
47
61
48
60
48
49
59
48
45
55
57
47
42
48
50
40
48
54
55
48
62
48
43
42
44
64
58
52
45
40
50
52
54
52
45
53
51
48
62
47
42
62
52
47
55
55
56
37
54
46
44
54
39
44
49
43
50
42
48
52
52
44
50
45
49
55
48
47
46
47
56
45
52
59
48
42
56
41
59
48
62
59
57
59
50
40
41
48
57
53
57
48
52
54
50'''.split(), dtype='int64')

In [22]:
hist40 = np.histogram(numbers40)
hist40

(array([ 2, 10, 11,  8, 23, 12, 10,  8,  7,  5], dtype=int64),
 array([37. , 39.7, 42.4, 45.1, 47.8, 50.5, 53.2, 55.9, 58.6, 61.3, 64. ]))

In [23]:
s = '''4	5	6	7	8	9	10	11	12	13	14	15	16	17	18	19	20	21	22	29
1	5	1	11	21	35	46	34	48	34	47	36	21	17	12	6	3	7	2	1'''
hist10 = [np.array(x.split(), dtype=int) for x in s.split('\n')]
hist10

[array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 29]),
 array([ 1,  5,  1, 11, 21, 35, 46, 34, 48, 34, 47, 36, 21, 17, 12,  6,  3,
         7,  2,  1])]

In [24]:
numbers10 = []
for i in range(len(hist10[0])):
    for j in range(hist10[1][i]):
        numbers10.append(hist10[0][i])

In [24]:



mean = np.mean(numbers10)

In [26]:
np.mean(np.square(numbers10-np.mean(numbers10)))

11.960516526729725

In [29]:
print(np.sqrt(np.mean(np.square(numbers40-np.mean(numbers40)))))
print(np.mean(np.square(numbers40)) - np.mean(numbers40)**2)
print(np.mean(numbers40))

6.126479058947498
37.533745659722626
50.197916666666664


In [34]:
for a in [numbers10, numbers40]:
    m = np.mean(a)
    print("Mean =", m)
    sigm = np.sqrt(np.mean(np.square(a-np.mean(a))))
    print("Sigma =", sigm)
    print("2 Sigma =", 2*sigm) 
    n = len(a)
    print("N =", n)
    inS = np.count_nonzero(np.bitwise_and((m - sigm < a), (a < m + sigm)))
    print("In sigma is ", inS, "which is", inS/n)

    inDS = np.count_nonzero(np.bitwise_and((m - 2*sigm < a), (a < m + 2*sigm)))
    print("In 2 sigma is ", inDS, "which is", inDS/n)
    print("Next!!\n")

Mean = 12.577319587628866
Sigma = 3.4583979711319697
2 Sigma = 6.916795942263939
N = 388
In sigma is  266 which is 0.6855670103092784
In 2 sigma is  369 which is 0.9510309278350515
Next!!

Mean = 50.197916666666664
Sigma = 6.126479058947498
2 Sigma = 12.252958117894996
N = 96
In sigma is  61 which is 0.6354166666666666
In 2 sigma is  94 which is 0.9791666666666666
Next!!



In [32]:
numbers40 < 10


array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])